title: Estadísticas MIGRA
logo: assets/img/logo (2).png
description: Núcleo Milenio de investigación sobre temáticas de migración en Chile.
show_downloads: false
theme: jekyll-theme-minimal


# Navigation links
navigation:
  - title: "Principal"
    url: https://datamigra.cl/ # Link to your external page

plugins:
  - jekyll-feed
